-- =====================================================================
--  StemVault – 06_seed.sql  (generated by tools/generate_seed.py)
--  Fictional data. Every login password: StemVault@123
--  Dates are relative to CURDATE() so the data stays consistent.
-- =====================================================================
USE stemvault;
SET @app_user_id = NULL;

-- users -----------------------------------------------------------------
INSERT INTO `user` (user_id, username, password_hash, role, status, created_at) VALUES
(1, 'admin', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'ADMIN', 'ACTIVE', NOW() - INTERVAL 3000 DAY),
(2, 'staff.kavya', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'BANK_STAFF', 'ACTIVE', NOW() - INTERVAL 2000 DAY),
(3, 'staff.rahul', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'BANK_STAFF', 'ACTIVE', NOW() - INTERVAL 2000 DAY),
(4, 'staff.meera', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'BANK_STAFF', 'ACTIVE', NOW() - INTERVAL 2000 DAY),
(5, 'staff.imran', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'BANK_STAFF', 'ACTIVE', NOW() - INTERVAL 2000 DAY),
(6, 'dr.ananya', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(7, 'dr.vikram', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(8, 'dr.farah', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(9, 'dr.senthil', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(10, 'dr.lakshmi', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(11, 'dr.rohan', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(12, 'dr.deepa', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(13, 'dr.joseph', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(14, 'dr.aditi', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(15, 'dr.nikhil', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(16, 'dr.harpreet', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(17, 'dr.sravani', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(18, 'dr.arindam', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DOCTOR', 'ACTIVE', NOW() - INTERVAL 1500 DAY),
(19, 'patient.arjun', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'PATIENT', 'ACTIVE', NOW() - INTERVAL 120 DAY),
(20, 'donor.priya', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DONOR', 'ACTIVE', NOW() - INTERVAL 630 DAY),
(21, 'patient.meena', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'PATIENT', 'ACTIVE', NOW() - INTERVAL 60 DAY),
(22, 'donor.karthik', '$2a$10$h58GjpqukFaIlDcbcR5gGO8EhuK/0kw2VKit86aR7tzFljnkllqta', 'DONOR', 'ACTIVE', NOW() - INTERVAL 489 DAY);
SET @app_user_id = 1;  -- audit rows below are attributed to the admin

-- hospitals -------------------------------------------------------------
INSERT INTO hospital (hospital_id, hospital_name, registration_no, address_line, city, district, state, pincode, phone, email, registered_on, status) VALUES
(1, 'Marina Coast Multispeciality Hospital', 'TN-HSP-1001', '12 Beach Road', 'Chennai', 'Chennai', 'Tamil Nadu', '600004', '04424561001', 'contact@marinacoast.example.in', CURDATE() - INTERVAL 2400 DAY, 'ACTIVE'),
(2, 'Adyar Stem Cell & Transplant Centre', 'TN-HSP-1002', '45 Gandhi Nagar Main Road', 'Chennai', 'Chennai', 'Tamil Nadu', '600020', '04424561002', 'info@adyarstemcell.example.in', CURDATE() - INTERVAL 2100 DAY, 'ACTIVE'),
(3, 'Kovai Regional Cancer Institute', 'TN-HSP-1003', '8 Avinashi Road', 'Coimbatore', 'Coimbatore', 'Tamil Nadu', '641014', '04224561003', 'desk@kovaicancer.example.in', CURDATE() - INTERVAL 1900 DAY, 'ACTIVE'),
(4, 'Meenakshi Hematology Hospital', 'TN-HSP-1004', '21 Anna Nagar', 'Madurai', 'Madurai', 'Tamil Nadu', '625020', '04524561004', 'care@meenakshihem.example.in', CURDATE() - INTERVAL 1500 DAY, 'ACTIVE'),
(5, 'Deccan Blood & Marrow Institute', 'KA-HSP-2001', '90 Hosur Road', 'Bengaluru', 'Bengaluru Urban', 'Karnataka', '560034', '08024562001', 'hello@deccanbmi.example.in', CURDATE() - INTERVAL 2200 DAY, 'ACTIVE'),
(6, 'Chamundi Medical College Hospital', 'KA-HSP-2002', '3 Irwin Road', 'Mysuru', 'Mysuru', 'Karnataka', '570001', '08214562002', 'office@chamundimch.example.in', CURDATE() - INTERVAL 1700 DAY, 'ACTIVE'),
(7, 'Periyar Riverside Hospital', 'KL-HSP-3001', '14 MG Road', 'Kochi', 'Ernakulam', 'Kerala', '682016', '04844563001', 'contact@periyarriverside.example.in', CURDATE() - INTERVAL 1600 DAY, 'ACTIVE'),
(8, 'Arabian Sea Cancer Centre', 'MH-HSP-4001', '77 Linking Road', 'Mumbai', 'Mumbai Suburban', 'Maharashtra', '400050', '02224564001', 'info@arabiansea.example.in', CURDATE() - INTERVAL 2600 DAY, 'ACTIVE'),
(9, 'Sahyadri Transplant Hospital', 'MH-HSP-4002', '5 FC Road', 'Pune', 'Pune', 'Maharashtra', '411004', '02024564002', 'desk@sahyadritx.example.in', CURDATE() - INTERVAL 1400 DAY, 'ACTIVE'),
(10, 'Yamuna National Stem Cell Bank', 'DL-HSP-5001', '1 Ring Road', 'New Delhi', 'New Delhi', 'Delhi', '110029', '01124565001', 'bank@yamunastemcell.example.in', CURDATE() - INTERVAL 2900 DAY, 'ACTIVE'),
(11, 'Charminar Bone Marrow Centre', 'TG-HSP-6001', '30 Road No 2, Banjara Hills', 'Hyderabad', 'Hyderabad', 'Telangana', '500034', '04024566001', 'care@charminarbmc.example.in', CURDATE() - INTERVAL 1800 DAY, 'ACTIVE'),
(12, 'Hooghly Riverside Cancer Hospital', 'WB-HSP-7001', '18 Park Street', 'Kolkata', 'Kolkata', 'West Bengal', '700016', '03324567001', 'info@hooghlycancer.example.in', CURDATE() - INTERVAL 2000 DAY, 'ACTIVE'),
(13, 'Konkan Coastal Hospital', 'MH-HSP-4003', '9 Station Road', 'Ratnagiri', 'Ratnagiri', 'Maharashtra', '415612', '02352564003', 'admin@konkancoastal.example.in', CURDATE() - INTERVAL 900 DAY, 'ACTIVE');

-- storage units ---------------------------------------------------------
INSERT INTO storage_location (location_id, hospital_id, location_code, storage_area, storage_type, capacity) VALUES
(1, 1, 'CHN-MC-LN2-01', 'Cryo room, block B', 'LN2_VAPOUR', 60),
(2, 2, 'CHN-AD-LN2-01', 'Main cryobank hall', 'LN2_LIQUID', 120),
(3, 2, 'CHN-AD-LN2-02', 'Main cryobank hall', 'LN2_VAPOUR', 80),
(4, 3, 'CBE-KR-LN2-01', 'Hematology lab annex', 'LN2_VAPOUR', 60),
(5, 4, 'MDU-MH-ULT-01', 'Processing lab', 'ULT_FREEZER', 30),
(6, 5, 'BLR-DB-LN2-01', 'Cryobank level 2', 'LN2_LIQUID', 100),
(7, 7, 'COK-PR-LN2-01', 'Stem cell lab', 'LN2_VAPOUR', 50),
(8, 8, 'BOM-AS-LN2-01', 'Cryobank wing C', 'LN2_LIQUID', 100),
(9, 9, 'PNQ-SH-LN2-01', 'Transplant unit store', 'LN2_VAPOUR', 40),
(10, 10, 'DEL-YN-LN2-01', 'National repository hall 1', 'LN2_LIQUID', 200),
(11, 10, 'DEL-YN-LN2-02', 'National repository hall 2', 'LN2_LIQUID', 200),
(12, 11, 'HYD-CB-LN2-01', 'BMT cryo lab', 'LN2_VAPOUR', 80),
(13, 12, 'CCU-HR-LN2-01', 'Oncology cryo store', 'LN2_VAPOUR', 60);

-- doctors ---------------------------------------------------------------
INSERT INTO doctor (doctor_id, user_id, hospital_id, full_name, specialization, medical_reg_no, phone, email) VALUES
(1, 6, 1, 'Dr. Ananya Raghavan', 'Clinical Hematology', 'TNMC-48213', '8820297021', 'ananya@doctors.example.in'),
(2, 7, 1, 'Dr. Vikram Sundaram', 'Bone Marrow Transplantation', 'TNMC-51877', '9556909275', 'vikram@doctors.example.in'),
(3, 8, 2, 'Dr. Farah Siddiqui', 'Pediatric Hemato-Oncology', 'TNMC-60342', '8719285654', 'farah@doctors.example.in'),
(4, 9, 3, 'Dr. Senthil Kumar', 'Medical Oncology', 'TNMC-39021', '9102786814', 'senthil@doctors.example.in'),
(5, 10, 4, 'Dr. Lakshmi Narayanan', 'Clinical Hematology', 'TNMC-44109', '8739473121', 'lakshmi@doctors.example.in'),
(6, 11, 5, 'Dr. Rohan Hegde', 'Bone Marrow Transplantation', 'KMC-72290', '8271551884', 'rohan@doctors.example.in'),
(7, 12, 6, 'Dr. Deepa Urs', 'Clinical Hematology', 'KMC-68814', '8225831323', 'deepa@doctors.example.in'),
(8, 13, 7, 'Dr. Joseph Mathew', 'Hemato-Oncology', 'TCMC-33457', '8058957829', 'joseph@doctors.example.in'),
(9, 14, 8, 'Dr. Aditi Kulkarni', 'Bone Marrow Transplantation', 'MMC-90126', '9146786691', 'aditi@doctors.example.in'),
(10, 15, 9, 'Dr. Nikhil Deshpande', 'Clinical Hematology', 'MMC-87543', '9517785289', 'nikhil@doctors.example.in'),
(11, 16, 10, 'Dr. Harpreet Sethi', 'Bone Marrow Transplantation', 'DMC-25518', '9268018242', 'harpreet@doctors.example.in'),
(12, 17, 11, 'Dr. Sravani Reddy', 'Pediatric Bone Marrow Transplantation', 'TSMC-41962', '9535841438', 'sravani@doctors.example.in'),
(13, 18, 12, 'Dr. Arindam Bose', 'Medical Oncology', 'WBMC-57730', '8249818299', 'arindam@doctors.example.in');

-- donors ----------------------------------------------------------------
INSERT INTO donor (donor_id, user_id, full_name, date_of_birth, gender, blood_group, hla_a_1, hla_a_2, hla_b_1, hla_b_2, hla_drb1_1, hla_drb1_2, phone, email, address, registration_date, status) VALUES
(1, NULL, 'Revathi Bhat', '1988-05-26', 'F', 'O+', 'A*26:01', 'A*01:01', 'B*57:01', 'B*07:02', 'DRB1*04:01', 'DRB1*11:01', '9265423511', 'revathi.bhat1@mail.example.in', 'Station Road, No. 89', CURDATE() - INTERVAL 601 DAY, 'ACTIVE'),
(2, NULL, 'Fathima Das', '1984-02-02', 'F', 'A-', 'A*26:01', 'A*02:01', 'B*57:01', 'B*07:02', 'DRB1*04:01', 'DRB1*11:01', '9413164752', 'fathima.das2@mail.example.in', 'MG Road, No. 172', CURDATE() - INTERVAL 782 DAY, 'ACTIVE'),
(3, NULL, 'Revathi Khan', '1980-01-08', 'F', 'O+', 'A*26:01', 'A*01:01', 'B*57:01', 'B*07:02', 'DRB1*04:01', 'DRB1*11:01', '9564139537', 'revathi.khan3@mail.example.in', 'Lake View Road, No. 118', CURDATE() - INTERVAL 694 DAY, 'ACTIVE'),
(4, NULL, 'Rahul Mishra', '1982-05-25', 'M', 'A-', 'A*31:01', 'A*11:01', 'B*52:01', 'B*44:03', 'DRB1*14:01', 'DRB1*15:01', '8146270482', 'rahul.mishra4@mail.example.in', 'Anna Salai, No. 161', CURDATE() - INTERVAL 783 DAY, 'ACTIVE'),
(5, NULL, 'Priya Nair', '1995-05-08', 'F', 'O+', 'A*31:01', 'A*01:01', 'B*52:01', 'B*51:01', 'DRB1*14:01', 'DRB1*15:01', '9911718227', NULL, 'MG Road, No. 68', CURDATE() - INTERVAL 665 DAY, 'ACTIVE'),
(6, NULL, 'Swathi Joshi', '1992-09-15', 'F', 'O+', 'A*31:01', 'A*24:02', 'B*52:01', 'B*44:03', 'DRB1*14:01', 'DRB1*15:01', '9331509839', 'swathi.joshi6@mail.example.in', 'Anna Salai, No. 162', CURDATE() - INTERVAL 865 DAY, 'ACTIVE'),
(7, NULL, 'Prakash Das', '1989-08-05', 'M', 'O+', 'A*68:01', 'A*24:02', 'B*37:01', 'B*15:01', 'DRB1*10:01', 'DRB1*13:02', '8247317810', NULL, 'Temple Road, No. 4', CURDATE() - INTERVAL 555 DAY, 'ACTIVE'),
(8, NULL, 'Priya Chatterjee', '1998-08-10', 'F', 'AB+', 'A*68:01', 'A*01:01', 'B*37:01', 'B*15:01', 'DRB1*10:01', 'DRB1*13:02', '7872343098', 'priya.chatterjee8@mail.example.in', 'Station Road, No. 15', CURDATE() - INTERVAL 584 DAY, 'ACTIVE'),
(9, NULL, 'Meghana Patel', '1992-09-23', 'F', 'AB+', 'A*32:01', 'A*11:01', 'B*13:01', 'B*15:01', 'DRB1*16:02', 'DRB1*11:01', '8980841241', NULL, 'Lake View Road, No. 142', CURDATE() - INTERVAL 625 DAY, 'ACTIVE'),
(10, NULL, 'Shalini Menon', '2004-11-14', 'F', 'B-', 'A*32:01', 'A*24:02', 'B*13:01', 'B*15:01', 'DRB1*16:02', 'DRB1*11:01', '8005242786', 'shalini.menon10@mail.example.in', 'Anna Salai, No. 20', CURDATE() - INTERVAL 758 DAY, 'ACTIVE'),
(11, NULL, 'Ritika Gupta', '1998-03-26', 'F', 'O+', 'A*03:01', 'A*02:01', 'B*18:01', 'B*07:02', 'DRB1*01:01', 'DRB1*11:01', '7160733754', NULL, 'MG Road, No. 58', CURDATE() - INTERVAL 877 DAY, 'ACTIVE'),
(12, 20, 'Abdul Iyer', '1990-09-22', 'M', 'O+', 'A*30:01', 'A*11:01', 'B*27:05', 'B*51:01', 'DRB1*09:01', 'DRB1*13:02', '7356159514', 'abdul.iyer12@mail.example.in', 'Lake View Road, No. 105', CURDATE() - INTERVAL 630 DAY, 'ACTIVE'),
(13, NULL, 'Imran Shetty', '1985-11-20', 'M', 'B+', 'A*23:01', 'A*24:02', 'B*08:01', 'B*51:01', 'DRB1*08:03', 'DRB1*07:01', '8134332003', NULL, 'Temple Road, No. 19', CURDATE() - INTERVAL 837 DAY, 'ACTIVE'),
(14, 22, 'Suresh Shetty', '1986-06-01', 'M', 'B-', 'A*02:01', 'A*01:01', 'B*07:02', 'B*40:06', 'DRB1*07:01', 'DRB1*07:01', '8716572628', NULL, 'Station Road, No. 158', CURDATE() - INTERVAL 489 DAY, 'ACTIVE'),
(15, NULL, 'Sanjay Bhat', '1999-08-19', 'M', 'O-', 'A*02:01', 'A*24:02', 'B*07:02', 'B*40:06', 'DRB1*07:01', 'DRB1*07:01', '7650752735', NULL, 'Station Road, No. 72', CURDATE() - INTERVAL 425 DAY, 'ACTIVE'),
(16, NULL, 'Neha Bhat', '1981-01-03', 'F', 'A+', 'A*02:01', 'A*02:01', 'B*07:02', 'B*15:01', 'DRB1*07:01', 'DRB1*07:01', '9634957885', 'neha.bhat16@mail.example.in', 'Lake View Road, No. 141', CURDATE() - INTERVAL 508 DAY, 'ACTIVE'),
(17, NULL, 'Sneha Reddy', '1994-08-03', 'F', 'O-', 'A*24:02', 'A*24:02', 'B*40:06', 'B*35:01', 'DRB1*07:01', 'DRB1*03:01', '7022941318', NULL, 'Temple Road, No. 153', CURDATE() - INTERVAL 637 DAY, 'ACTIVE'),
(18, NULL, 'Divya Gupta', '1997-12-10', 'F', 'A-', 'A*01:01', 'A*02:01', 'B*07:02', 'B*40:06', 'DRB1*15:01', 'DRB1*13:02', '8134936183', NULL, 'Station Road, No. 37', CURDATE() - INTERVAL 1082 DAY, 'ACTIVE'),
(19, NULL, 'Abdul Khan', '1987-05-01', 'M', 'O+', 'A*11:01', 'A*33:03', 'B*44:03', 'B*40:06', 'DRB1*15:01', 'DRB1*03:01', '9990490278', NULL, 'Station Road, No. 47', CURDATE() - INTERVAL 1344 DAY, 'ACTIVE'),
(20, NULL, 'Ritika Menon', '2000-09-12', 'F', 'O-', 'A*11:01', 'A*11:01', 'B*35:01', 'B*07:02', 'DRB1*15:01', 'DRB1*13:02', '8703482477', 'ritika.menon20@mail.example.in', 'Lake View Road, No. 156', CURDATE() - INTERVAL 122 DAY, 'ACTIVE'),
(21, NULL, 'Manoj Reddy', '1998-07-11', 'M', 'B-', 'A*24:02', 'A*24:02', 'B*15:01', 'B*40:06', 'DRB1*13:02', 'DRB1*07:01', '7404499727', 'manoj.reddy21@mail.example.in', 'Station Road, No. 86', CURDATE() - INTERVAL 905 DAY, 'ACTIVE'),
(22, NULL, 'Varun Menon', '2002-09-19', 'M', 'A+', 'A*24:02', 'A*01:01', 'B*35:01', 'B*51:01', 'DRB1*15:01', 'DRB1*15:01', '9718702621', 'varun.menon22@mail.example.in', 'Station Road, No. 87', CURDATE() - INTERVAL 910 DAY, 'ACTIVE'),
(23, NULL, 'Priya Menon', '1996-01-10', 'F', 'A+', 'A*01:01', 'A*24:02', 'B*07:02', 'B*51:01', 'DRB1*03:01', 'DRB1*15:01', '8623869222', 'priya.menon23@mail.example.in', 'Nehru Street, No. 159', CURDATE() - INTERVAL 460 DAY, 'ACTIVE'),
(24, NULL, 'Vishal Rao', '1984-05-01', 'M', 'B-', 'A*24:02', 'A*11:01', 'B*40:06', 'B*35:01', 'DRB1*07:01', 'DRB1*15:01', '7640909743', NULL, 'Station Road, No. 57', CURDATE() - INTERVAL 1109 DAY, 'ACTIVE'),
(25, NULL, 'Nandini Pillai', '1980-08-26', 'F', 'A+', 'A*02:01', 'A*02:01', 'B*15:01', 'B*44:03', 'DRB1*11:01', 'DRB1*13:02', '7517123685', 'nandini.pillai25@mail.example.in', 'Nehru Street, No. 4', CURDATE() - INTERVAL 1147 DAY, 'ACTIVE'),
(26, NULL, 'Suresh Bhat', '1984-05-21', 'M', 'AB+', 'A*02:01', 'A*24:02', 'B*07:02', 'B*44:03', 'DRB1*13:02', 'DRB1*11:01', '9200471138', 'suresh.bhat26@mail.example.in', 'Nehru Street, No. 95', CURDATE() - INTERVAL 1369 DAY, 'ACTIVE'),
(27, NULL, 'Shalini Das', '2003-08-03', 'F', 'A-', 'A*11:01', 'A*01:01', 'B*51:01', 'B*35:01', 'DRB1*13:02', 'DRB1*11:01', '9900532931', NULL, 'Temple Road, No. 54', CURDATE() - INTERVAL 405 DAY, 'ACTIVE'),
(28, NULL, 'Ajay Pillai', '2005-03-24', 'M', 'AB+', 'A*01:01', 'A*02:01', 'B*07:02', 'B*35:01', 'DRB1*07:01', 'DRB1*13:02', '7117758917', 'ajay.pillai28@mail.example.in', 'Temple Road, No. 12', CURDATE() - INTERVAL 783 DAY, 'ACTIVE'),
(29, NULL, 'Harini Shetty', '1987-07-04', 'F', 'B-', 'A*33:03', 'A*33:03', 'B*51:01', 'B*35:01', 'DRB1*15:01', 'DRB1*13:02', '7183673657', 'harini.shetty29@mail.example.in', 'Lake View Road, No. 25', CURDATE() - INTERVAL 1206 DAY, 'ACTIVE'),
(30, NULL, 'Gautham Nair', '1993-06-28', 'M', 'A-', 'A*01:01', 'A*24:02', 'B*07:02', 'B*51:01', 'DRB1*11:01', 'DRB1*07:01', '8049451983', 'gautham.nair30@mail.example.in', 'Nehru Street, No. 58', CURDATE() - INTERVAL 1259 DAY, 'ACTIVE'),
(31, NULL, 'Manoj Chatterjee', '2004-03-24', 'M', 'A-', 'A*02:01', 'A*11:01', 'B*51:01', 'B*35:01', 'DRB1*11:01', 'DRB1*11:01', '9183667525', 'manoj.chatterjee31@mail.example.in', 'Station Road, No. 146', CURDATE() - INTERVAL 132 DAY, 'ACTIVE'),
(32, NULL, 'Ritika Nair', '1997-11-22', 'F', 'O-', 'A*33:03', 'A*24:02', 'B*40:06', 'B*35:01', 'DRB1*07:01', 'DRB1*13:02', '8840369003', 'ritika.nair32@mail.example.in', 'MG Road, No. 36', CURDATE() - INTERVAL 353 DAY, 'ACTIVE'),
(33, NULL, 'Sneha Chatterjee', '2006-06-06', 'F', 'B-', 'A*01:01', 'A*11:01', 'B*44:03', 'B*40:06', 'DRB1*13:02', 'DRB1*15:01', '7751613696', 'sneha.chatterjee33@mail.example.in', 'Nehru Street, No. 80', CURDATE() - INTERVAL 975 DAY, 'ACTIVE'),
(34, NULL, 'Aishwarya Bhat', '2004-08-15', 'F', 'A-', 'A*01:01', 'A*02:01', 'B*51:01', 'B*40:06', 'DRB1*15:01', 'DRB1*13:02', '8490581477', 'aishwarya.bhat34@mail.example.in', 'Station Road, No. 74', CURDATE() - INTERVAL 1306 DAY, 'ACTIVE'),
(35, NULL, 'Aishwarya Menon', '1992-02-26', 'F', 'B-', 'A*01:01', 'A*24:02', 'B*44:03', 'B*51:01', 'DRB1*07:01', 'DRB1*11:01', '8182037788', NULL, 'Station Road, No. 96', CURDATE() - INTERVAL 1359 DAY, 'ACTIVE'),
(36, NULL, 'Aishwarya Reddy', '1997-09-13', 'F', 'A-', 'A*02:01', 'A*11:01', 'B*07:02', 'B*44:03', 'DRB1*07:01', 'DRB1*11:01', '8281685054', 'aishwarya.reddy36@mail.example.in', 'MG Road, No. 88', CURDATE() - INTERVAL 755 DAY, 'ACTIVE'),
(37, NULL, 'Abdul Joshi', '1985-12-08', 'M', 'AB+', 'A*02:01', 'A*02:01', 'B*15:01', 'B*51:01', 'DRB1*13:02', 'DRB1*07:01', '7473834735', NULL, 'Temple Road, No. 113', CURDATE() - INTERVAL 1016 DAY, 'ACTIVE'),
(38, NULL, 'Imran Reddy', '1982-03-09', 'M', 'AB+', 'A*11:01', 'A*01:01', 'B*51:01', 'B*40:06', 'DRB1*11:01', 'DRB1*13:02', '7261375060', 'imran.reddy38@mail.example.in', 'Station Road, No. 61', CURDATE() - INTERVAL 405 DAY, 'ACTIVE'),
(39, NULL, 'Arun Pillai', '2000-03-18', 'M', 'A-', 'A*24:02', 'A*02:01', 'B*51:01', 'B*40:06', 'DRB1*15:01', 'DRB1*13:02', '7861434103', 'arun.pillai39@mail.example.in', 'Temple Road, No. 118', CURDATE() - INTERVAL 130 DAY, 'ACTIVE'),
(40, NULL, 'Vishal Reddy', '1990-09-17', 'M', 'B-', 'A*01:01', 'A*33:03', 'B*35:01', 'B*15:01', 'DRB1*13:02', 'DRB1*15:01', '7806706540', 'vishal.reddy40@mail.example.in', 'Anna Salai, No. 89', CURDATE() - INTERVAL 503 DAY, 'ACTIVE'),
(41, NULL, 'Gautham Rao', '1990-07-27', 'M', 'O-', 'A*02:01', 'A*24:02', 'B*51:01', 'B*40:06', 'DRB1*07:01', 'DRB1*07:01', '8403450541', NULL, 'Nehru Street, No. 103', CURDATE() - INTERVAL 132 DAY, 'ACTIVE'),
(42, NULL, 'Anjali Patel', '1991-12-16', 'F', 'A+', 'A*01:01', 'A*24:02', 'B*07:02', 'B*35:01', 'DRB1*07:01', 'DRB1*03:01', '7416169284', 'anjali.patel42@mail.example.in', 'Anna Salai, No. 84', CURDATE() - INTERVAL 255 DAY, 'ACTIVE'),
(43, NULL, 'Meghana Bhat', '1987-12-14', 'F', 'B+', NULL, NULL, NULL, NULL, NULL, NULL, '7757059640', 'meghana.bhat43@mail.example.in', 'Lake View Road, No. 104', CURDATE() - INTERVAL 368 DAY, 'ACTIVE');

-- patients --------------------------------------------------------------
INSERT INTO patient (patient_id, user_id, full_name, date_of_birth, gender, blood_group, hla_a_1, hla_a_2, hla_b_1, hla_b_2, hla_drb1_1, hla_drb1_2, diagnosis, phone, email, address, registration_date, status) VALUES
(1, NULL, 'Manoj Nair', '1975-12-18', 'M', 'O+', 'A*26:01', 'A*01:01', 'B*57:01', 'B*07:02', 'DRB1*04:01', 'DRB1*11:01', 'Acute Lymphoblastic Leukemia', '7600133890', NULL, NULL, CURDATE() - INTERVAL 99 DAY, 'ACTIVE'),
(2, NULL, 'Manoj Shetty', '1987-02-25', 'M', 'O+', 'A*31:01', 'A*24:02', 'B*52:01', 'B*44:03', 'DRB1*14:01', 'DRB1*15:01', 'Severe Aplastic Anemia', '9226916697', NULL, NULL, CURDATE() - INTERVAL 103 DAY, 'ACTIVE'),
(3, NULL, 'Revathi Verma', '1992-04-04', 'F', 'O+', 'A*68:01', 'A*24:02', 'B*37:01', 'B*15:01', 'DRB1*10:01', 'DRB1*13:02', 'Multiple Myeloma', '7656670106', NULL, NULL, CURDATE() - INTERVAL 64 DAY, 'ACTIVE'),
(4, NULL, 'Naveen Chatterjee', '2011-10-08', 'M', 'O-', 'A*29:02', 'A*33:03', 'B*58:01', 'B*07:02', 'DRB1*12:01', 'DRB1*07:01', 'Beta Thalassemia Major', '7091699854', NULL, NULL, CURDATE() - INTERVAL 43 DAY, 'ACTIVE'),
(5, NULL, 'Imran Bhat', '1998-02-01', 'M', 'AB+', 'A*32:01', 'A*11:01', 'B*13:01', 'B*15:01', 'DRB1*16:02', 'DRB1*11:01', 'Acute Myeloid Leukemia', '7911838425', NULL, NULL, CURDATE() - INTERVAL 46 DAY, 'ACTIVE'),
(6, NULL, 'Vishal Das', '1975-04-22', 'M', 'O+', 'A*03:01', 'A*02:01', 'B*18:01', 'B*07:02', 'DRB1*01:01', 'DRB1*11:01', 'Myelodysplastic Syndrome', '8869232260', NULL, NULL, CURDATE() - INTERVAL 58 DAY, 'ACTIVE'),
(7, 19, 'Shalini Patel', '1981-05-02', 'F', 'O+', 'A*30:01', 'A*11:01', 'B*27:05', 'B*51:01', 'DRB1*09:01', 'DRB1*13:02', 'Fanconi Anemia', '7655698169', NULL, NULL, CURDATE() - INTERVAL 129 DAY, 'ACTIVE'),
(8, NULL, 'Swathi Mishra', '2018-05-10', 'F', 'B+', 'A*23:01', 'A*24:02', 'B*08:01', 'B*51:01', 'DRB1*08:03', 'DRB1*07:01', 'Chronic Myeloid Leukemia', '8995777387', NULL, NULL, CURDATE() - INTERVAL 140 DAY, 'ACTIVE'),
(9, 21, 'Sai Menon', '1987-04-28', 'M', 'O+', 'A*02:01', 'A*01:01', 'B*07:02', 'B*40:06', 'DRB1*07:01', 'DRB1*07:01', 'Juvenile Myelomonocytic Leukemia', '8278895798', NULL, NULL, CURDATE() - INTERVAL 100 DAY, 'ACTIVE'),
(10, NULL, 'Neha Gupta', '2005-08-03', 'F', 'A-', 'A*02:01', 'A*24:02', 'B*40:06', 'B*35:01', 'DRB1*07:01', 'DRB1*11:01', 'Hodgkin Lymphoma (relapsed)', '8345581223', NULL, NULL, CURDATE() - INTERVAL 95 DAY, 'ACTIVE'),
(11, NULL, 'Abdul Menon', '2009-07-13', 'M', 'B-', 'A*02:01', 'A*01:01', 'B*40:06', 'B*40:06', 'DRB1*11:01', 'DRB1*13:02', 'Acute Myeloid Leukemia', '7096705466', NULL, NULL, CURDATE() - INTERVAL 110 DAY, 'ACTIVE'),
(12, NULL, 'Gautham Chatterjee', '1976-03-27', 'M', 'AB+', 'A*24:02', 'A*02:01', 'B*35:01', 'B*40:06', 'DRB1*15:01', 'DRB1*03:01', 'Acute Lymphoblastic Leukemia', '9980699016', NULL, NULL, CURDATE() - INTERVAL 54 DAY, 'ACTIVE'),
(13, NULL, 'Anjali Khan', '1974-07-09', 'F', 'B-', 'A*02:01', 'A*01:01', 'B*35:01', 'B*40:06', 'DRB1*11:01', 'DRB1*07:01', 'Non-Hodgkin Lymphoma', '8417080531', NULL, NULL, CURDATE() - INTERVAL 47 DAY, 'ACTIVE'),
(14, NULL, 'Manoj Verma', '2009-10-07', 'M', 'AB+', NULL, NULL, NULL, NULL, NULL, NULL, 'Sickle Cell Disease', '7452991241', NULL, NULL, CURDATE() - INTERVAL 33 DAY, 'ACTIVE'),
(15, NULL, 'Swathi Chatterjee', '2004-02-19', 'F', 'A-', 'A*01:01', 'A*02:01', 'B*15:01', 'B*07:02', 'DRB1*13:02', 'DRB1*07:01', 'Aplastic Anemia (in remission)', '7314919058', NULL, NULL, CURDATE() - INTERVAL 239 DAY, 'ACTIVE');

-- consents -------------------------------------------------------------
INSERT INTO consent (donor_id, consent_type, consent_date, valid_until) VALUES
(1, 'COLLECTION', CURDATE() - INTERVAL 601 DAY, NULL),
(1, 'STORAGE', CURDATE() - INTERVAL 601 DAY, CURDATE() + INTERVAL 3049 DAY),
(1, 'CLINICAL_USE', CURDATE() - INTERVAL 601 DAY, NULL),
(2, 'COLLECTION', CURDATE() - INTERVAL 782 DAY, NULL),
(2, 'STORAGE', CURDATE() - INTERVAL 782 DAY, CURDATE() + INTERVAL 2868 DAY),
(2, 'CLINICAL_USE', CURDATE() - INTERVAL 782 DAY, NULL),
(3, 'COLLECTION', CURDATE() - INTERVAL 694 DAY, NULL),
(3, 'STORAGE', CURDATE() - INTERVAL 694 DAY, CURDATE() + INTERVAL 2956 DAY),
(3, 'CLINICAL_USE', CURDATE() - INTERVAL 694 DAY, NULL),
(4, 'COLLECTION', CURDATE() - INTERVAL 783 DAY, NULL),
(4, 'STORAGE', CURDATE() - INTERVAL 783 DAY, CURDATE() + INTERVAL 2867 DAY),
(4, 'CLINICAL_USE', CURDATE() - INTERVAL 783 DAY, NULL),
(5, 'COLLECTION', CURDATE() - INTERVAL 665 DAY, NULL),
(5, 'STORAGE', CURDATE() - INTERVAL 665 DAY, CURDATE() + INTERVAL 2985 DAY),
(5, 'CLINICAL_USE', CURDATE() - INTERVAL 665 DAY, NULL),
(6, 'COLLECTION', CURDATE() - INTERVAL 865 DAY, NULL),
(6, 'STORAGE', CURDATE() - INTERVAL 865 DAY, CURDATE() + INTERVAL 2785 DAY),
(6, 'CLINICAL_USE', CURDATE() - INTERVAL 865 DAY, NULL),
(7, 'COLLECTION', CURDATE() - INTERVAL 555 DAY, NULL),
(7, 'STORAGE', CURDATE() - INTERVAL 555 DAY, CURDATE() + INTERVAL 3095 DAY),
(7, 'CLINICAL_USE', CURDATE() - INTERVAL 555 DAY, NULL),
(8, 'COLLECTION', CURDATE() - INTERVAL 584 DAY, NULL),
(8, 'STORAGE', CURDATE() - INTERVAL 584 DAY, CURDATE() + INTERVAL 3066 DAY),
(8, 'CLINICAL_USE', CURDATE() - INTERVAL 584 DAY, NULL),
(9, 'COLLECTION', CURDATE() - INTERVAL 625 DAY, NULL),
(9, 'STORAGE', CURDATE() - INTERVAL 625 DAY, CURDATE() + INTERVAL 3025 DAY),
(9, 'CLINICAL_USE', CURDATE() - INTERVAL 625 DAY, NULL),
(10, 'COLLECTION', CURDATE() - INTERVAL 758 DAY, NULL),
(10, 'STORAGE', CURDATE() - INTERVAL 758 DAY, CURDATE() + INTERVAL 2892 DAY),
(10, 'CLINICAL_USE', CURDATE() - INTERVAL 758 DAY, NULL),
(11, 'COLLECTION', CURDATE() - INTERVAL 877 DAY, NULL),
(11, 'STORAGE', CURDATE() - INTERVAL 877 DAY, CURDATE() + INTERVAL 2773 DAY),
(11, 'CLINICAL_USE', CURDATE() - INTERVAL 877 DAY, NULL),
(12, 'COLLECTION', CURDATE() - INTERVAL 630 DAY, NULL),
(12, 'STORAGE', CURDATE() - INTERVAL 630 DAY, CURDATE() + INTERVAL 3020 DAY),
(12, 'CLINICAL_USE', CURDATE() - INTERVAL 630 DAY, NULL),
(13, 'COLLECTION', CURDATE() - INTERVAL 837 DAY, NULL),
(13, 'STORAGE', CURDATE() - INTERVAL 837 DAY, CURDATE() + INTERVAL 2813 DAY),
(13, 'CLINICAL_USE', CURDATE() - INTERVAL 837 DAY, NULL),
(14, 'COLLECTION', CURDATE() - INTERVAL 489 DAY, NULL),
(14, 'STORAGE', CURDATE() - INTERVAL 489 DAY, CURDATE() + INTERVAL 3161 DAY),
(14, 'CLINICAL_USE', CURDATE() - INTERVAL 489 DAY, NULL),
(15, 'COLLECTION', CURDATE() - INTERVAL 425 DAY, NULL),
(15, 'STORAGE', CURDATE() - INTERVAL 425 DAY, CURDATE() + INTERVAL 3225 DAY),
(15, 'CLINICAL_USE', CURDATE() - INTERVAL 425 DAY, NULL),
(16, 'COLLECTION', CURDATE() - INTERVAL 508 DAY, NULL),
(16, 'STORAGE', CURDATE() - INTERVAL 508 DAY, CURDATE() + INTERVAL 3142 DAY),
(16, 'CLINICAL_USE', CURDATE() - INTERVAL 508 DAY, NULL),
(17, 'COLLECTION', CURDATE() - INTERVAL 637 DAY, NULL),
(17, 'STORAGE', CURDATE() - INTERVAL 637 DAY, CURDATE() + INTERVAL 3013 DAY),
(17, 'CLINICAL_USE', CURDATE() - INTERVAL 637 DAY, NULL),
(18, 'COLLECTION', CURDATE() - INTERVAL 1082 DAY, NULL),
(18, 'STORAGE', CURDATE() - INTERVAL 1082 DAY, CURDATE() + INTERVAL 2568 DAY),
(18, 'CLINICAL_USE', CURDATE() - INTERVAL 1082 DAY, NULL),
(19, 'COLLECTION', CURDATE() - INTERVAL 1344 DAY, NULL),
(19, 'STORAGE', CURDATE() - INTERVAL 1344 DAY, CURDATE() + INTERVAL 2306 DAY),
(19, 'CLINICAL_USE', CURDATE() - INTERVAL 1344 DAY, NULL),
(20, 'COLLECTION', CURDATE() - INTERVAL 122 DAY, NULL),
(20, 'STORAGE', CURDATE() - INTERVAL 122 DAY, CURDATE() + INTERVAL 3528 DAY),
(20, 'CLINICAL_USE', CURDATE() - INTERVAL 122 DAY, NULL),
(21, 'COLLECTION', CURDATE() - INTERVAL 905 DAY, NULL),
(21, 'STORAGE', CURDATE() - INTERVAL 905 DAY, CURDATE() + INTERVAL 2745 DAY),
(21, 'CLINICAL_USE', CURDATE() - INTERVAL 905 DAY, NULL),
(22, 'COLLECTION', CURDATE() - INTERVAL 910 DAY, NULL),
(22, 'STORAGE', CURDATE() - INTERVAL 910 DAY, CURDATE() + INTERVAL 2740 DAY),
(22, 'CLINICAL_USE', CURDATE() - INTERVAL 910 DAY, NULL),
(23, 'COLLECTION', CURDATE() - INTERVAL 460 DAY, NULL),
(23, 'STORAGE', CURDATE() - INTERVAL 460 DAY, CURDATE() + INTERVAL 3190 DAY),
(23, 'CLINICAL_USE', CURDATE() - INTERVAL 460 DAY, NULL),
(24, 'COLLECTION', CURDATE() - INTERVAL 1109 DAY, NULL),
(24, 'STORAGE', CURDATE() - INTERVAL 1109 DAY, CURDATE() + INTERVAL 2541 DAY),
(24, 'CLINICAL_USE', CURDATE() - INTERVAL 1109 DAY, NULL),
(25, 'COLLECTION', CURDATE() - INTERVAL 1147 DAY, NULL),
(25, 'STORAGE', CURDATE() - INTERVAL 1147 DAY, CURDATE() + INTERVAL 2503 DAY),
(25, 'CLINICAL_USE', CURDATE() - INTERVAL 1147 DAY, NULL),
(26, 'COLLECTION', CURDATE() - INTERVAL 1369 DAY, NULL),
(26, 'STORAGE', CURDATE() - INTERVAL 1369 DAY, CURDATE() + INTERVAL 2281 DAY),
(26, 'CLINICAL_USE', CURDATE() - INTERVAL 1369 DAY, NULL),
(27, 'COLLECTION', CURDATE() - INTERVAL 405 DAY, NULL),
(27, 'STORAGE', CURDATE() - INTERVAL 405 DAY, CURDATE() + INTERVAL 3245 DAY),
(27, 'CLINICAL_USE', CURDATE() - INTERVAL 405 DAY, NULL),
(28, 'COLLECTION', CURDATE() - INTERVAL 783 DAY, NULL),
(28, 'STORAGE', CURDATE() - INTERVAL 783 DAY, CURDATE() + INTERVAL 2867 DAY),
(28, 'CLINICAL_USE', CURDATE() - INTERVAL 783 DAY, NULL),
(29, 'COLLECTION', CURDATE() - INTERVAL 1206 DAY, NULL),
(29, 'STORAGE', CURDATE() - INTERVAL 1206 DAY, CURDATE() + INTERVAL 2444 DAY),
(29, 'CLINICAL_USE', CURDATE() - INTERVAL 1206 DAY, NULL),
(30, 'COLLECTION', CURDATE() - INTERVAL 1259 DAY, NULL),
(30, 'STORAGE', CURDATE() - INTERVAL 1259 DAY, CURDATE() + INTERVAL 2391 DAY),
(30, 'CLINICAL_USE', CURDATE() - INTERVAL 1259 DAY, NULL),
(31, 'COLLECTION', CURDATE() - INTERVAL 132 DAY, NULL),
(31, 'STORAGE', CURDATE() - INTERVAL 132 DAY, CURDATE() + INTERVAL 3518 DAY),
(31, 'CLINICAL_USE', CURDATE() - INTERVAL 132 DAY, NULL),
(32, 'COLLECTION', CURDATE() - INTERVAL 353 DAY, NULL),
(32, 'STORAGE', CURDATE() - INTERVAL 353 DAY, CURDATE() + INTERVAL 3297 DAY),
(32, 'CLINICAL_USE', CURDATE() - INTERVAL 353 DAY, NULL),
(33, 'COLLECTION', CURDATE() - INTERVAL 975 DAY, NULL),
(33, 'STORAGE', CURDATE() - INTERVAL 975 DAY, CURDATE() + INTERVAL 2675 DAY),
(33, 'CLINICAL_USE', CURDATE() - INTERVAL 975 DAY, NULL),
(34, 'COLLECTION', CURDATE() - INTERVAL 1306 DAY, NULL),
(34, 'STORAGE', CURDATE() - INTERVAL 1306 DAY, CURDATE() + INTERVAL 2344 DAY),
(34, 'CLINICAL_USE', CURDATE() - INTERVAL 1306 DAY, NULL),
(35, 'COLLECTION', CURDATE() - INTERVAL 1359 DAY, NULL),
(35, 'STORAGE', CURDATE() - INTERVAL 1359 DAY, CURDATE() + INTERVAL 2291 DAY),
(35, 'CLINICAL_USE', CURDATE() - INTERVAL 1359 DAY, NULL),
(36, 'COLLECTION', CURDATE() - INTERVAL 755 DAY, NULL),
(36, 'STORAGE', CURDATE() - INTERVAL 755 DAY, CURDATE() - INTERVAL 2 DAY),
(36, 'CLINICAL_USE', CURDATE() - INTERVAL 755 DAY, NULL),
(37, 'COLLECTION', CURDATE() - INTERVAL 1016 DAY, NULL),
(37, 'STORAGE', CURDATE() - INTERVAL 1016 DAY, CURDATE() + INTERVAL 2634 DAY),
(37, 'CLINICAL_USE', CURDATE() - INTERVAL 1016 DAY, NULL),
(38, 'COLLECTION', CURDATE() - INTERVAL 405 DAY, NULL),
(38, 'STORAGE', CURDATE() - INTERVAL 405 DAY, CURDATE() + INTERVAL 3245 DAY),
(38, 'CLINICAL_USE', CURDATE() - INTERVAL 405 DAY, NULL),
(39, 'COLLECTION', CURDATE() - INTERVAL 130 DAY, NULL),
(39, 'STORAGE', CURDATE() - INTERVAL 130 DAY, CURDATE() + INTERVAL 3520 DAY),
(39, 'CLINICAL_USE', CURDATE() - INTERVAL 130 DAY, NULL),
(40, 'COLLECTION', CURDATE() - INTERVAL 503 DAY, NULL),
(40, 'STORAGE', CURDATE() - INTERVAL 503 DAY, CURDATE() + INTERVAL 3147 DAY),
(40, 'CLINICAL_USE', CURDATE() - INTERVAL 503 DAY, NULL),
(41, 'COLLECTION', CURDATE() - INTERVAL 132 DAY, NULL),
(42, 'COLLECTION', CURDATE() - INTERVAL 255 DAY, NULL),
(43, 'COLLECTION', CURDATE() - INTERVAL 368 DAY, NULL);

-- samples: collected, then tested, then released through sp_release_sample
INSERT INTO stem_cell_sample (sample_id, donor_id, sample_type, collection_date, volume_ml, cd34_count, processing_status, expiry_date) VALUES
(1, 1, 'CORD_BLOOD', CURDATE() - INTERVAL 553 DAY, 73, 4.03, 'PROCESSING', NULL),
(2, 2, 'CORD_BLOOD', CURDATE() - INTERVAL 755 DAY, 49, 2.44, 'PROCESSING', NULL),
(3, 3, 'CORD_BLOOD', CURDATE() - INTERVAL 675 DAY, 73, 5.6, 'PROCESSING', NULL),
(4, 4, 'BONE_MARROW', CURDATE() - INTERVAL 754 DAY, 1223, 7.46, 'PROCESSING', CURDATE() + INTERVAL 1071 DAY),
(5, 5, 'BONE_MARROW', CURDATE() - INTERVAL 622 DAY, 1033, 7.41, 'PROCESSING', CURDATE() + INTERVAL 1203 DAY),
(6, 6, 'BONE_MARROW', CURDATE() - INTERVAL 852 DAY, 669, 2.96, 'PROCESSING', CURDATE() + INTERVAL 973 DAY),
(7, 7, 'PBSC', CURDATE() - INTERVAL 540 DAY, 254, 8.01, 'PROCESSING', CURDATE() + INTERVAL 1285 DAY),
(8, 8, 'PBSC', CURDATE() - INTERVAL 571 DAY, 278, 4.57, 'PROCESSING', CURDATE() + INTERVAL 1254 DAY),
(9, 9, 'PBSC', CURDATE() - INTERVAL 606 DAY, 304, 10.87, 'PROCESSING', CURDATE() + INTERVAL 1219 DAY),
(10, 10, 'PBSC', CURDATE() - INTERVAL 704 DAY, 159, 5.48, 'PROCESSING', CURDATE() + INTERVAL 1121 DAY),
(11, 11, 'BONE_MARROW', CURDATE() - INTERVAL 866 DAY, 1008, 2.95, 'PROCESSING', CURDATE() + INTERVAL 959 DAY),
(12, 12, 'CORD_BLOOD', CURDATE() - INTERVAL 600 DAY, 91, 4.55, 'PROCESSING', NULL),
(13, 13, 'BONE_MARROW', CURDATE() - INTERVAL 798 DAY, 1244, 7.03, 'PROCESSING', CURDATE() + INTERVAL 1027 DAY),
(14, 14, 'CORD_BLOOD', CURDATE() - INTERVAL 469 DAY, 108, 4.06, 'PROCESSING', NULL),
(15, 15, 'CORD_BLOOD', CURDATE() - INTERVAL 405 DAY, 116, 3.02, 'PROCESSING', NULL),
(16, 16, 'CORD_BLOOD', CURDATE() - INTERVAL 488 DAY, 82, 4.0, 'PROCESSING', NULL),
(17, 17, 'PBSC', CURDATE() - INTERVAL 584 DAY, 259, 10.1, 'PROCESSING', CURDATE() - INTERVAL 31 DAY),
(18, 17, 'PBSC', CURDATE() - INTERVAL 606 DAY, 217, 5.74, 'PROCESSING', CURDATE() + INTERVAL 1219 DAY),
(19, 18, 'CORD_BLOOD', CURDATE() - INTERVAL 1001 DAY, 112, NULL, 'QUARANTINE', NULL),
(20, 19, 'BONE_MARROW', CURDATE() - INTERVAL 1277 DAY, 1018, 3.18, 'PROCESSING', CURDATE() - INTERVAL 33 DAY),
(21, 19, 'BONE_MARROW', CURDATE() - INTERVAL 1276 DAY, 1278, 6.08, 'PROCESSING', CURDATE() + INTERVAL 549 DAY),
(22, 20, 'PBSC', CURDATE() - INTERVAL 78 DAY, 291, 12.41, 'PROCESSING', CURDATE() + INTERVAL 1747 DAY),
(23, 20, 'CORD_BLOOD', CURDATE() - INTERVAL 102 DAY, 59, 3.11, 'PROCESSING', NULL),
(24, 21, 'PBSC', CURDATE() - INTERVAL 842 DAY, 328, 12.56, 'PROCESSING', CURDATE() + INTERVAL 983 DAY),
(25, 22, 'BONE_MARROW', CURDATE() - INTERVAL 895 DAY, 1290, 8.7, 'PROCESSING', CURDATE() + INTERVAL 930 DAY),
(26, 22, 'BONE_MARROW', CURDATE() - INTERVAL 901 DAY, 670, 8.49, 'PROCESSING', CURDATE() + INTERVAL 924 DAY),
(27, 23, 'BONE_MARROW', CURDATE() - INTERVAL 437 DAY, 1072, 4.16, 'PROCESSING', CURDATE() + INTERVAL 1388 DAY),
(28, 23, 'BONE_MARROW', CURDATE() - INTERVAL 369 DAY, 761, 4.75, 'PROCESSING', CURDATE() + INTERVAL 1456 DAY),
(29, 24, 'PBSC', CURDATE() - INTERVAL 1018 DAY, 174, NULL, 'QUARANTINE', CURDATE() + INTERVAL 807 DAY),
(30, 24, 'BONE_MARROW', CURDATE() - INTERVAL 1030 DAY, 1349, 4.42, 'PROCESSING', CURDATE() + INTERVAL 795 DAY),
(31, 25, 'CORD_BLOOD', CURDATE() - INTERVAL 1095 DAY, 73, 6.02, 'PROCESSING', NULL),
(32, 26, 'PBSC', CURDATE() - INTERVAL 1295 DAY, 340, NULL, 'QUARANTINE', CURDATE() + INTERVAL 530 DAY),
(33, 26, 'BONE_MARROW', CURDATE() - INTERVAL 1312 DAY, 633, 5.38, 'PROCESSING', CURDATE() + INTERVAL 513 DAY),
(34, 27, 'BONE_MARROW', CURDATE() - INTERVAL 400 DAY, 733, 3.63, 'PROCESSING', CURDATE() + INTERVAL 18 DAY),
(35, 28, 'PBSC', CURDATE() - INTERVAL 740 DAY, 272, 5.08, 'PROCESSING', CURDATE() + INTERVAL 45 DAY),
(36, 28, 'PBSC', CURDATE() - INTERVAL 769 DAY, 305, 10.24, 'PROCESSING', CURDATE() + INTERVAL 1056 DAY),
(37, 29, 'BONE_MARROW', CURDATE() - INTERVAL 1169 DAY, 756, 2.94, 'PROCESSING', CURDATE() + INTERVAL 656 DAY),
(38, 30, 'BONE_MARROW', CURDATE() - INTERVAL 1207 DAY, 1380, 7.75, 'PROCESSING', CURDATE() + INTERVAL 618 DAY),
(39, 30, 'PBSC', CURDATE() - INTERVAL 1168 DAY, 305, 6.67, 'PROCESSING', CURDATE() + INTERVAL 657 DAY),
(40, 31, 'CORD_BLOOD', CURDATE() - INTERVAL 107 DAY, 119, 1.95, 'PROCESSING', NULL),
(41, 32, 'BONE_MARROW', CURDATE() - INTERVAL 333 DAY, 1109, 3.34, 'PROCESSING', CURDATE() + INTERVAL 1492 DAY),
(42, 32, 'CORD_BLOOD', CURDATE() - INTERVAL 277 DAY, 85, 6.24, 'PROCESSING', NULL),
(43, 33, 'CORD_BLOOD', CURDATE() - INTERVAL 949 DAY, 49, 2.13, 'PROCESSING', NULL),
(44, 33, 'BONE_MARROW', CURDATE() - INTERVAL 877 DAY, 841, 3.78, 'PROCESSING', CURDATE() + INTERVAL 948 DAY),
(45, 34, 'CORD_BLOOD', CURDATE() - INTERVAL 1225 DAY, 104, 4.69, 'PROCESSING', NULL),
(46, 35, 'BONE_MARROW', CURDATE() - INTERVAL 1311 DAY, 653, 4.68, 'PROCESSING', CURDATE() + INTERVAL 514 DAY),
(47, 35, 'PBSC', CURDATE() - INTERVAL 1305 DAY, 335, 10.03, 'PROCESSING', CURDATE() + INTERVAL 520 DAY),
(48, 36, 'BONE_MARROW', CURDATE() - INTERVAL 722 DAY, 758, 7.62, 'PROCESSING', CURDATE() + INTERVAL 1103 DAY),
(49, 36, 'PBSC', CURDATE() - INTERVAL 683 DAY, 236, 9.97, 'PROCESSING', CURDATE() + INTERVAL 1142 DAY),
(50, 37, 'BONE_MARROW', CURDATE() - INTERVAL 947 DAY, 1028, 7.71, 'PROCESSING', CURDATE() + INTERVAL 878 DAY),
(51, 38, 'BONE_MARROW', CURDATE() - INTERVAL 400 DAY, 1331, 3.45, 'PROCESSING', CURDATE() + INTERVAL 18 DAY),
(52, 39, 'BONE_MARROW', CURDATE() - INTERVAL 57 DAY, 1247, 7.17, 'PROCESSING', CURDATE() + INTERVAL 1768 DAY),
(53, 40, 'PBSC', CURDATE() - INTERVAL 485 DAY, 343, 9.46, 'PROCESSING', CURDATE() + INTERVAL 1340 DAY);

-- laboratory tests ------------------------------------------------------
INSERT INTO sample_test (sample_id, test_type, test_date, result, test_status, remarks, performed_by) VALUES
(1, 'HLA_TYPING', NOW() - INTERVAL 13224 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(1, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 13221 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(1, 'STERILITY', NOW() - INTERVAL 13218 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(1, 'VIABILITY', NOW() - INTERVAL 13215 HOUR, '98% viable (7-AAD)', 'PASSED', NULL, 3),
(1, 'CD34_COUNT', NOW() - INTERVAL 13212 HOUR, '4.03', 'PASSED', NULL, 3),
(2, 'HLA_TYPING', NOW() - INTERVAL 18048 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(2, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 18045 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(2, 'STERILITY', NOW() - INTERVAL 18042 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(2, 'VIABILITY', NOW() - INTERVAL 18039 HOUR, '88% viable (7-AAD)', 'PASSED', NULL, 2),
(2, 'CD34_COUNT', NOW() - INTERVAL 18036 HOUR, '2.44', 'PASSED', NULL, 2),
(3, 'HLA_TYPING', NOW() - INTERVAL 16176 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(3, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 16173 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(3, 'STERILITY', NOW() - INTERVAL 16170 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(3, 'VIABILITY', NOW() - INTERVAL 16167 HOUR, '98% viable (7-AAD)', 'PASSED', NULL, 2),
(3, 'CD34_COUNT', NOW() - INTERVAL 16164 HOUR, '5.6', 'PASSED', NULL, 2),
(4, 'HLA_TYPING', NOW() - INTERVAL 18024 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(4, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 18021 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(4, 'STERILITY', NOW() - INTERVAL 18018 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(4, 'VIABILITY', NOW() - INTERVAL 18015 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 3),
(4, 'CD34_COUNT', NOW() - INTERVAL 18012 HOUR, '7.46', 'PASSED', NULL, 3),
(5, 'HLA_TYPING', NOW() - INTERVAL 14832 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(5, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 14829 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(5, 'STERILITY', NOW() - INTERVAL 14826 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(5, 'VIABILITY', NOW() - INTERVAL 14823 HOUR, '95% viable (7-AAD)', 'PASSED', NULL, 2),
(5, 'CD34_COUNT', NOW() - INTERVAL 14820 HOUR, '7.41', 'PASSED', NULL, 2),
(6, 'HLA_TYPING', NOW() - INTERVAL 20376 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(6, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 20373 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(6, 'STERILITY', NOW() - INTERVAL 20370 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(6, 'VIABILITY', NOW() - INTERVAL 20367 HOUR, '95% viable (7-AAD)', 'PASSED', NULL, 4),
(6, 'CD34_COUNT', NOW() - INTERVAL 20364 HOUR, '2.96', 'PASSED', NULL, 4),
(7, 'HLA_TYPING', NOW() - INTERVAL 12912 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(7, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 12909 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(7, 'STERILITY', NOW() - INTERVAL 12906 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(7, 'VIABILITY', NOW() - INTERVAL 12903 HOUR, '92% viable (7-AAD)', 'PASSED', NULL, 5),
(7, 'CD34_COUNT', NOW() - INTERVAL 12900 HOUR, '8.01', 'PASSED', NULL, 5),
(8, 'HLA_TYPING', NOW() - INTERVAL 13608 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(8, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 13605 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(8, 'STERILITY', NOW() - INTERVAL 13602 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(8, 'VIABILITY', NOW() - INTERVAL 13599 HOUR, '88% viable (7-AAD)', 'PASSED', NULL, 2),
(8, 'CD34_COUNT', NOW() - INTERVAL 13596 HOUR, '4.57', 'PASSED', NULL, 2),
(9, 'HLA_TYPING', NOW() - INTERVAL 14496 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(9, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 14493 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(9, 'STERILITY', NOW() - INTERVAL 14490 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(9, 'VIABILITY', NOW() - INTERVAL 14487 HOUR, '94% viable (7-AAD)', 'PASSED', NULL, 5),
(9, 'CD34_COUNT', NOW() - INTERVAL 14484 HOUR, '10.87', 'PASSED', NULL, 5),
(10, 'HLA_TYPING', NOW() - INTERVAL 16800 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(10, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 16797 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(10, 'STERILITY', NOW() - INTERVAL 16794 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(10, 'VIABILITY', NOW() - INTERVAL 16791 HOUR, '91% viable (7-AAD)', 'PASSED', NULL, 5),
(10, 'CD34_COUNT', NOW() - INTERVAL 16788 HOUR, '5.48', 'PASSED', NULL, 5),
(11, 'HLA_TYPING', NOW() - INTERVAL 20712 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(11, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 20709 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(11, 'STERILITY', NOW() - INTERVAL 20706 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(11, 'VIABILITY', NOW() - INTERVAL 20703 HOUR, '93% viable (7-AAD)', 'PASSED', NULL, 3),
(11, 'CD34_COUNT', NOW() - INTERVAL 20700 HOUR, '2.95', 'PASSED', NULL, 3),
(12, 'HLA_TYPING', NOW() - INTERVAL 14328 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(12, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 14325 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(12, 'STERILITY', NOW() - INTERVAL 14322 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(12, 'VIABILITY', NOW() - INTERVAL 14319 HOUR, '94% viable (7-AAD)', 'PASSED', NULL, 4),
(12, 'CD34_COUNT', NOW() - INTERVAL 14316 HOUR, '4.55', 'PASSED', NULL, 4),
(13, 'HLA_TYPING', NOW() - INTERVAL 19104 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(13, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 19101 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(13, 'STERILITY', NOW() - INTERVAL 19098 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(13, 'VIABILITY', NOW() - INTERVAL 19095 HOUR, '96% viable (7-AAD)', 'PASSED', NULL, 4),
(13, 'CD34_COUNT', NOW() - INTERVAL 19092 HOUR, '7.03', 'PASSED', NULL, 4),
(14, 'HLA_TYPING', NOW() - INTERVAL 11232 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(14, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 11229 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(14, 'STERILITY', NOW() - INTERVAL 11226 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(14, 'VIABILITY', NOW() - INTERVAL 11223 HOUR, '91% viable (7-AAD)', 'PASSED', NULL, 4),
(14, 'CD34_COUNT', NOW() - INTERVAL 11220 HOUR, '4.06', 'PASSED', NULL, 4),
(15, 'HLA_TYPING', NOW() - INTERVAL 9624 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(15, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 9621 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(15, 'STERILITY', NOW() - INTERVAL 9618 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(15, 'VIABILITY', NOW() - INTERVAL 9615 HOUR, '92% viable (7-AAD)', 'PASSED', NULL, 2),
(15, 'CD34_COUNT', NOW() - INTERVAL 9612 HOUR, '3.02', 'PASSED', NULL, 2),
(16, 'HLA_TYPING', NOW() - INTERVAL 11616 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(16, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 11613 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(16, 'STERILITY', NOW() - INTERVAL 11610 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(16, 'VIABILITY', NOW() - INTERVAL 11607 HOUR, '90% viable (7-AAD)', 'PASSED', NULL, 3),
(16, 'CD34_COUNT', NOW() - INTERVAL 11604 HOUR, '4.0', 'PASSED', NULL, 3),
(17, 'HLA_TYPING', NOW() - INTERVAL 13992 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(17, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 13989 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(17, 'STERILITY', NOW() - INTERVAL 13986 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(17, 'VIABILITY', NOW() - INTERVAL 13983 HOUR, '92% viable (7-AAD)', 'PASSED', NULL, 2),
(17, 'CD34_COUNT', NOW() - INTERVAL 13980 HOUR, '10.1', 'PASSED', NULL, 2),
(18, 'HLA_TYPING', NOW() - INTERVAL 14448 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(18, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 14445 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(18, 'STERILITY', NOW() - INTERVAL 14442 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(18, 'VIABILITY', NOW() - INTERVAL 14439 HOUR, '91% viable (7-AAD)', 'PASSED', NULL, 5),
(18, 'CD34_COUNT', NOW() - INTERVAL 14436 HOUR, '5.74', 'PASSED', NULL, 5),
(19, 'HLA_TYPING', NOW() - INTERVAL 23976 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(19, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 23973 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(19, 'STERILITY', NOW() - INTERVAL 23970 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(19, 'VIABILITY', NOW() - INTERVAL 23967 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(19, 'CD34_COUNT', NOW() - INTERVAL 23964 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(20, 'HLA_TYPING', NOW() - INTERVAL 30576 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(20, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 30573 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(20, 'STERILITY', NOW() - INTERVAL 30570 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(20, 'VIABILITY', NOW() - INTERVAL 30567 HOUR, '90% viable (7-AAD)', 'PASSED', NULL, 3),
(20, 'CD34_COUNT', NOW() - INTERVAL 30564 HOUR, '3.18', 'PASSED', NULL, 3),
(21, 'HLA_TYPING', NOW() - INTERVAL 30528 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(21, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 30525 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(21, 'STERILITY', NOW() - INTERVAL 30522 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(21, 'VIABILITY', NOW() - INTERVAL 30519 HOUR, '95% viable (7-AAD)', 'PASSED', NULL, 5),
(21, 'CD34_COUNT', NOW() - INTERVAL 30516 HOUR, '6.08', 'PASSED', NULL, 5),
(22, 'HLA_TYPING', NOW() - INTERVAL 1800 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(22, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 1797 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(22, 'STERILITY', NOW() - INTERVAL 1794 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(22, 'VIABILITY', NOW() - INTERVAL 1791 HOUR, '88% viable (7-AAD)', 'PASSED', NULL, 5),
(22, 'CD34_COUNT', NOW() - INTERVAL 1788 HOUR, '12.41', 'PASSED', NULL, 5),
(23, 'HLA_TYPING', NOW() - INTERVAL 2424 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(23, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 2421 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(23, 'STERILITY', NOW() - INTERVAL 2418 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(23, 'VIABILITY', NOW() - INTERVAL 2415 HOUR, '96% viable (7-AAD)', 'PASSED', NULL, 5),
(23, 'CD34_COUNT', NOW() - INTERVAL 2412 HOUR, '3.11', 'PASSED', NULL, 5),
(24, 'HLA_TYPING', NOW() - INTERVAL 20112 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(24, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 20109 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(24, 'STERILITY', NOW() - INTERVAL 20106 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(24, 'VIABILITY', NOW() - INTERVAL 20103 HOUR, '91% viable (7-AAD)', 'PASSED', NULL, 3),
(24, 'CD34_COUNT', NOW() - INTERVAL 20100 HOUR, '12.56', 'PASSED', NULL, 3),
(25, 'HLA_TYPING', NOW() - INTERVAL 21408 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(25, 'STERILITY', NOW() - INTERVAL 21402 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(25, 'VIABILITY', NOW() - INTERVAL 21399 HOUR, '88% viable (7-AAD)', 'PASSED', NULL, 2),
(25, 'CD34_COUNT', NOW() - INTERVAL 21396 HOUR, '8.7', 'PASSED', NULL, 2),
(25, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 21405 HOUR, 'HBsAg reactive', 'FAILED', 'Confirmed on repeat; unit to be discarded', 2),
(26, 'HLA_TYPING', NOW() - INTERVAL 21552 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(26, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 21549 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(26, 'STERILITY', NOW() - INTERVAL 21546 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(26, 'VIABILITY', NOW() - INTERVAL 21543 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 5),
(26, 'CD34_COUNT', NOW() - INTERVAL 21540 HOUR, '8.49', 'PASSED', NULL, 5),
(27, 'HLA_TYPING', NOW() - INTERVAL 10392 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(27, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 10389 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(27, 'STERILITY', NOW() - INTERVAL 10386 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(27, 'VIABILITY', NOW() - INTERVAL 10383 HOUR, '96% viable (7-AAD)', 'PASSED', NULL, 4),
(27, 'CD34_COUNT', NOW() - INTERVAL 10380 HOUR, '4.16', 'PASSED', NULL, 4),
(28, 'HLA_TYPING', NOW() - INTERVAL 8832 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(28, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 8829 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(28, 'STERILITY', NOW() - INTERVAL 8826 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(28, 'VIABILITY', NOW() - INTERVAL 8823 HOUR, '94% viable (7-AAD)', 'PASSED', NULL, 2),
(28, 'CD34_COUNT', NOW() - INTERVAL 8820 HOUR, '4.75', 'PASSED', NULL, 2),
(29, 'HLA_TYPING', NOW() - INTERVAL 24384 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(29, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 24381 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(29, 'STERILITY', NOW() - INTERVAL 24378 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(29, 'VIABILITY', NOW() - INTERVAL 24375 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(29, 'CD34_COUNT', NOW() - INTERVAL 24372 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(30, 'HLA_TYPING', NOW() - INTERVAL 24648 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(30, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 24645 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(30, 'STERILITY', NOW() - INTERVAL 24642 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(30, 'VIABILITY', NOW() - INTERVAL 24639 HOUR, '93% viable (7-AAD)', 'PASSED', NULL, 5),
(30, 'CD34_COUNT', NOW() - INTERVAL 24636 HOUR, '4.42', 'PASSED', NULL, 5),
(31, 'HLA_TYPING', NOW() - INTERVAL 26256 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(31, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 26253 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(31, 'STERILITY', NOW() - INTERVAL 26250 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(31, 'VIABILITY', NOW() - INTERVAL 26247 HOUR, '88% viable (7-AAD)', 'PASSED', NULL, 5),
(31, 'CD34_COUNT', NOW() - INTERVAL 26244 HOUR, '6.02', 'PASSED', NULL, 5),
(32, 'HLA_TYPING', NOW() - INTERVAL 31032 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(32, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 31029 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(32, 'STERILITY', NOW() - INTERVAL 31026 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(32, 'VIABILITY', NOW() - INTERVAL 31023 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(32, 'CD34_COUNT', NOW() - INTERVAL 31020 HOUR, NULL, 'PENDING', 'Awaiting result', 4),
(33, 'HLA_TYPING', NOW() - INTERVAL 31416 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(33, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 31413 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(33, 'STERILITY', NOW() - INTERVAL 31410 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(33, 'VIABILITY', NOW() - INTERVAL 31407 HOUR, '94% viable (7-AAD)', 'PASSED', NULL, 2),
(33, 'CD34_COUNT', NOW() - INTERVAL 31404 HOUR, '5.38', 'PASSED', NULL, 2),
(34, 'HLA_TYPING', NOW() - INTERVAL 9504 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(34, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 9501 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(34, 'STERILITY', NOW() - INTERVAL 9498 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(34, 'VIABILITY', NOW() - INTERVAL 9495 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 4),
(34, 'CD34_COUNT', NOW() - INTERVAL 9492 HOUR, '3.63', 'PASSED', NULL, 4),
(35, 'HLA_TYPING', NOW() - INTERVAL 17736 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(35, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 17733 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(35, 'STERILITY', NOW() - INTERVAL 17730 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(35, 'VIABILITY', NOW() - INTERVAL 17727 HOUR, '89% viable (7-AAD)', 'PASSED', NULL, 3),
(35, 'CD34_COUNT', NOW() - INTERVAL 17724 HOUR, '5.08', 'PASSED', NULL, 3),
(36, 'HLA_TYPING', NOW() - INTERVAL 18360 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(36, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 18357 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(36, 'STERILITY', NOW() - INTERVAL 18354 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(36, 'VIABILITY', NOW() - INTERVAL 18351 HOUR, '93% viable (7-AAD)', 'PASSED', NULL, 4),
(36, 'CD34_COUNT', NOW() - INTERVAL 18348 HOUR, '10.24', 'PASSED', NULL, 4),
(37, 'HLA_TYPING', NOW() - INTERVAL 27984 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(37, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 27981 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(37, 'STERILITY', NOW() - INTERVAL 27978 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(37, 'VIABILITY', NOW() - INTERVAL 27975 HOUR, '91% viable (7-AAD)', 'PASSED', NULL, 3),
(37, 'CD34_COUNT', NOW() - INTERVAL 27972 HOUR, '2.94', 'PASSED', NULL, 3),
(38, 'HLA_TYPING', NOW() - INTERVAL 28872 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(38, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 28869 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(38, 'STERILITY', NOW() - INTERVAL 28866 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(38, 'VIABILITY', NOW() - INTERVAL 28863 HOUR, '88% viable (7-AAD)', 'PASSED', NULL, 2),
(38, 'CD34_COUNT', NOW() - INTERVAL 28860 HOUR, '7.75', 'PASSED', NULL, 2),
(39, 'HLA_TYPING', NOW() - INTERVAL 28008 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(39, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 28005 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(39, 'STERILITY', NOW() - INTERVAL 28002 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(39, 'VIABILITY', NOW() - INTERVAL 27999 HOUR, '93% viable (7-AAD)', 'PASSED', NULL, 3),
(39, 'CD34_COUNT', NOW() - INTERVAL 27996 HOUR, '6.67', 'PASSED', NULL, 3),
(40, 'HLA_TYPING', NOW() - INTERVAL 2472 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(40, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 2469 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(40, 'STERILITY', NOW() - INTERVAL 2466 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(40, 'VIABILITY', NOW() - INTERVAL 2463 HOUR, '90% viable (7-AAD)', 'PASSED', NULL, 5),
(40, 'CD34_COUNT', NOW() - INTERVAL 2460 HOUR, '1.95', 'PASSED', NULL, 5),
(41, 'HLA_TYPING', NOW() - INTERVAL 7944 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(41, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 7941 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(41, 'STERILITY', NOW() - INTERVAL 7938 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(41, 'VIABILITY', NOW() - INTERVAL 7935 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 4),
(41, 'CD34_COUNT', NOW() - INTERVAL 7932 HOUR, '3.34', 'PASSED', NULL, 4),
(42, 'HLA_TYPING', NOW() - INTERVAL 6576 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(42, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 6573 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(42, 'STERILITY', NOW() - INTERVAL 6570 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(42, 'VIABILITY', NOW() - INTERVAL 6567 HOUR, '94% viable (7-AAD)', 'PASSED', NULL, 3),
(42, 'CD34_COUNT', NOW() - INTERVAL 6564 HOUR, '6.24', 'PASSED', NULL, 3),
(43, 'HLA_TYPING', NOW() - INTERVAL 22704 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(43, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 22701 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(43, 'STERILITY', NOW() - INTERVAL 22698 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(43, 'VIABILITY', NOW() - INTERVAL 22695 HOUR, '96% viable (7-AAD)', 'PASSED', NULL, 4),
(43, 'CD34_COUNT', NOW() - INTERVAL 22692 HOUR, '2.13', 'PASSED', NULL, 4),
(44, 'HLA_TYPING', NOW() - INTERVAL 20952 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(44, 'STERILITY', NOW() - INTERVAL 20946 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(44, 'VIABILITY', NOW() - INTERVAL 20943 HOUR, '95% viable (7-AAD)', 'PASSED', NULL, 4),
(44, 'CD34_COUNT', NOW() - INTERVAL 20940 HOUR, '3.78', 'PASSED', NULL, 4),
(44, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 20949 HOUR, 'HBsAg reactive', 'FAILED', 'Confirmed on repeat; unit to be discarded', 4),
(45, 'HLA_TYPING', NOW() - INTERVAL 29376 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(45, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 29373 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(45, 'STERILITY', NOW() - INTERVAL 29370 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(45, 'VIABILITY', NOW() - INTERVAL 29367 HOUR, '93% viable (7-AAD)', 'PASSED', NULL, 4),
(45, 'CD34_COUNT', NOW() - INTERVAL 29364 HOUR, '4.69', 'PASSED', NULL, 4),
(46, 'HLA_TYPING', NOW() - INTERVAL 31440 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 5),
(46, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 31437 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 5),
(46, 'STERILITY', NOW() - INTERVAL 31434 HOUR, 'No growth at 14 days', 'PASSED', NULL, 5),
(46, 'VIABILITY', NOW() - INTERVAL 31431 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 5),
(46, 'CD34_COUNT', NOW() - INTERVAL 31428 HOUR, '4.68', 'PASSED', NULL, 5),
(47, 'HLA_TYPING', NOW() - INTERVAL 31248 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(47, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 31245 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(47, 'STERILITY', NOW() - INTERVAL 31242 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(47, 'VIABILITY', NOW() - INTERVAL 31239 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 2),
(47, 'CD34_COUNT', NOW() - INTERVAL 31236 HOUR, '10.03', 'PASSED', NULL, 2),
(48, 'HLA_TYPING', NOW() - INTERVAL 17232 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 4),
(48, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 17229 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 4),
(48, 'STERILITY', NOW() - INTERVAL 17226 HOUR, 'No growth at 14 days', 'PASSED', NULL, 4),
(48, 'VIABILITY', NOW() - INTERVAL 17223 HOUR, '98% viable (7-AAD)', 'PASSED', NULL, 4),
(48, 'CD34_COUNT', NOW() - INTERVAL 17220 HOUR, '7.62', 'PASSED', NULL, 4),
(49, 'HLA_TYPING', NOW() - INTERVAL 16344 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(49, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 16341 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(49, 'STERILITY', NOW() - INTERVAL 16338 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(49, 'VIABILITY', NOW() - INTERVAL 16335 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 2),
(49, 'CD34_COUNT', NOW() - INTERVAL 16332 HOUR, '9.97', 'PASSED', NULL, 2),
(50, 'HLA_TYPING', NOW() - INTERVAL 22632 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(50, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 22629 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(50, 'STERILITY', NOW() - INTERVAL 22626 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(50, 'VIABILITY', NOW() - INTERVAL 22623 HOUR, '96% viable (7-AAD)', 'PASSED', NULL, 3),
(50, 'CD34_COUNT', NOW() - INTERVAL 22620 HOUR, '7.71', 'PASSED', NULL, 3),
(51, 'HLA_TYPING', NOW() - INTERVAL 9504 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(51, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 9501 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(51, 'STERILITY', NOW() - INTERVAL 9498 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(51, 'VIABILITY', NOW() - INTERVAL 9495 HOUR, '98% viable (7-AAD)', 'PASSED', NULL, 3),
(51, 'CD34_COUNT', NOW() - INTERVAL 9492 HOUR, '3.45', 'PASSED', NULL, 3),
(52, 'HLA_TYPING', NOW() - INTERVAL 1320 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 2),
(52, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 1317 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 2),
(52, 'STERILITY', NOW() - INTERVAL 1314 HOUR, 'No growth at 14 days', 'PASSED', NULL, 2),
(52, 'VIABILITY', NOW() - INTERVAL 1311 HOUR, '97% viable (7-AAD)', 'PASSED', NULL, 2),
(52, 'CD34_COUNT', NOW() - INTERVAL 1308 HOUR, '7.17', 'PASSED', NULL, 2),
(53, 'HLA_TYPING', NOW() - INTERVAL 11616 HOUR, 'Typed at A, B, DRB1 (high resolution)', 'PASSED', NULL, 3),
(53, 'INFECTIOUS_SCREEN', NOW() - INTERVAL 11613 HOUR, 'HIV, HBV, HCV, syphilis, CMV negative', 'PASSED', NULL, 3),
(53, 'STERILITY', NOW() - INTERVAL 11610 HOUR, 'No growth at 14 days', 'PASSED', NULL, 3),
(53, 'VIABILITY', NOW() - INTERVAL 11607 HOUR, '88% viable (7-AAD)', 'PASSED', NULL, 3),
(53, 'CD34_COUNT', NOW() - INTERVAL 11604 HOUR, '9.46', 'PASSED', NULL, 3);

-- release tested samples into storage (procedure checks tests, consent, capacity)
CALL sp_release_sample(1, 2, 'R01-B01-S01');
CALL sp_release_sample(2, 1, 'R01-B01-S01');
CALL sp_release_sample(3, 4, 'R01-B01-S01');
CALL sp_release_sample(4, 4, 'R01-B01-S02');
CALL sp_release_sample(5, 3, 'R01-B01-S01');
CALL sp_release_sample(6, 10, 'R01-B01-S01');
CALL sp_release_sample(7, 10, 'R01-B01-S02');
CALL sp_release_sample(8, 8, 'R01-B01-S01');
CALL sp_release_sample(9, 6, 'R01-B01-S01');
CALL sp_release_sample(10, 6, 'R01-B01-S02');
CALL sp_release_sample(11, 8, 'R01-B01-S02');
CALL sp_release_sample(12, 12, 'R01-B01-S01');
CALL sp_release_sample(13, 13, 'R01-B01-S01');
CALL sp_release_sample(14, 2, 'R01-B01-S02');
CALL sp_release_sample(15, 1, 'R01-B01-S02');
CALL sp_release_sample(16, 6, 'R01-B01-S03');
CALL sp_release_sample(18, 2, 'R01-B01-S03');
CALL sp_release_sample(21, 13, 'R01-B01-S02');
CALL sp_release_sample(22, 3, 'R01-B01-S02');
CALL sp_release_sample(23, 9, 'R01-B01-S01');
CALL sp_release_sample(24, 8, 'R01-B01-S03');
CALL sp_release_sample(26, 10, 'R01-B01-S03');
CALL sp_release_sample(27, 11, 'R01-B01-S01');
CALL sp_release_sample(28, 6, 'R01-B01-S04');
CALL sp_release_sample(30, 1, 'R01-B01-S03');
CALL sp_release_sample(31, 9, 'R01-B01-S02');
CALL sp_release_sample(33, 11, 'R01-B01-S02');
CALL sp_release_sample(34, 7, 'R01-B01-S01');
CALL sp_release_sample(35, 10, 'R01-B01-S04');
CALL sp_release_sample(36, 9, 'R01-B01-S03');
CALL sp_release_sample(37, 12, 'R01-B01-S02');
CALL sp_release_sample(38, 10, 'R01-B01-S05');
CALL sp_release_sample(39, 11, 'R01-B01-S03');
CALL sp_release_sample(40, 3, 'R01-B01-S03');
CALL sp_release_sample(41, 7, 'R01-B01-S02');
CALL sp_release_sample(42, 10, 'R01-B01-S06');
CALL sp_release_sample(43, 7, 'R01-B01-S03');
CALL sp_release_sample(45, 11, 'R01-B01-S04');
CALL sp_release_sample(46, 8, 'R01-B01-S04');
CALL sp_release_sample(47, 12, 'R01-B01-S03');
CALL sp_release_sample(48, 4, 'R01-B01-S03');
CALL sp_release_sample(49, 13, 'R01-B01-S03');
CALL sp_release_sample(50, 8, 'R01-B01-S05');
CALL sp_release_sample(51, 7, 'R01-B01-S04');
CALL sp_release_sample(52, 11, 'R01-B01-S05');
CALL sp_release_sample(53, 12, 'R01-B01-S04');

-- past-expiry units: stored but not offered; the maintenance job expires them
UPDATE stem_cell_sample SET processing_status = 'RELEASED', location_id = 10, storage_position = 'R01-B01-S07' WHERE sample_id = 17;
UPDATE stem_cell_sample SET processing_status = 'RELEASED', location_id = 12, storage_position = 'R01-B01-S05' WHERE sample_id = 20;

-- consent revocation withdraws that donor's available units (trigger)
CALL sp_revoke_consent((SELECT consent_id FROM consent WHERE donor_id = 17 AND consent_type = 'CLINICAL_USE'), 'Donor asked to withdraw from clinical use');
CALL sp_daily_maintenance(1);

-- transplant requests ---------------------------------------------------
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (1, 1, 1, NOW() - INTERVAL 18 DAY, 'CORD_BLOOD', 4, 'URGENT');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (2, 2, 5, NOW() - INTERVAL 26 DAY, 'BONE_MARROW', 4, 'CRITICAL');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (3, 3, 8, NOW() - INTERVAL 11 DAY, 'PBSC', 4, 'URGENT');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (4, 4, 7, NOW() - INTERVAL 7 DAY, 'CORD_BLOOD', 4, 'ROUTINE');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (5, 5, 6, NOW() - INTERVAL 28 DAY, 'PBSC', 4, 'CRITICAL');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (6, 6, 10, NOW() - INTERVAL 26 DAY, 'BONE_MARROW', 4, 'URGENT');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (7, 7, 12, NOW() - INTERVAL 95 DAY, 'CORD_BLOOD', 4, 'CRITICAL');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (8, 8, 11, NOW() - INTERVAL 109 DAY, 'BONE_MARROW', 4, 'URGENT');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (9, 9, 2, NOW() - INTERVAL 36 DAY, 'CORD_BLOOD', 4, 'CRITICAL');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (10, 10, 9, NOW() - INTERVAL 36 DAY, 'PBSC', 4, 'ROUTINE');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (11, 11, 4, NOW() - INTERVAL 32 DAY, 'BONE_MARROW', 4, 'URGENT');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (12, 12, 3, NOW() - INTERVAL 27 DAY, 'CORD_BLOOD', 4, 'ROUTINE');
INSERT INTO transplant_request (request_id, patient_id, doctor_id, request_date, required_sample_type, min_hla_match, urgency) VALUES (13, 13, 13, NOW() - INTERVAL 32 DAY, 'PBSC', 4, 'URGENT');

-- reviews ---------------------------------------------------------------
CALL sp_review_request(1, 2, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 1;
CALL sp_review_request(2, 2, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 2;
CALL sp_review_request(3, 2, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 3;
CALL sp_review_request(4, 1, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 4;
CALL sp_review_request(5, 2, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 5;
CALL sp_review_request(6, 3, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 6;
CALL sp_review_request(7, 1, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 7;
CALL sp_review_request(8, 2, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 8;
CALL sp_review_request(12, 3, 'REJECTED', 'Patient not in remission yet; resubmit after induction therapy');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 12;
CALL sp_review_request(13, 3, 'APPROVED', 'Clinical criteria met');
UPDATE transplant_request SET reviewed_at = request_date + INTERVAL 1 DAY WHERE request_id = 13;

-- tiered search + shortlist (sp_find_candidates saves the nearest tier) ---
CALL sp_find_candidates(1, 1);
CALL sp_find_candidates(2, 1);
CALL sp_find_candidates(3, 1);
CALL sp_find_candidates(4, 1);
CALL sp_find_candidates(5, 1);

-- allocations, transplants ---------------------------------------------
CALL sp_allocate_sample(5, 9);
UPDATE request_sample SET allocation_date = (SELECT request_date + INTERVAL 3 DAY FROM transplant_request WHERE request_id = 5) WHERE request_id = 5 AND sample_id = 9;
CALL sp_allocate_sample(6, 11);
UPDATE request_sample SET allocation_date = (SELECT request_date + INTERVAL 3 DAY FROM transplant_request WHERE request_id = 6) WHERE request_id = 6 AND sample_id = 11;
CALL sp_schedule_transplant(6, CURDATE() + INTERVAL 10 DAY, 'Conditioning regimen starts one week before', @t);
CALL sp_allocate_sample(7, 12);
UPDATE request_sample SET allocation_date = (SELECT request_date + INTERVAL 3 DAY FROM transplant_request WHERE request_id = 7) WHERE request_id = 7 AND sample_id = 12;
CALL sp_schedule_transplant(7, CURDATE() - INTERVAL 75 DAY, 'Myeloablative conditioning', @t);
CALL sp_complete_transplant(@t, 'ENGRAFTED', 'Neutrophil engraftment on day +18');
CALL sp_allocate_sample(8, 13);
UPDATE request_sample SET allocation_date = (SELECT request_date + INTERVAL 3 DAY FROM transplant_request WHERE request_id = 8) WHERE request_id = 8 AND sample_id = 13;
CALL sp_schedule_transplant(8, CURDATE() - INTERVAL 89 DAY, 'Myeloablative conditioning', @t);
CALL sp_complete_transplant(@t, 'COMPLICATIONS', 'Grade II acute GVHD, responding to steroids');

-- a cancelled request ----------------------------------------------------
CALL sp_cancel_request(13, 'Patient transferred to another centre');

-- one storage unit taken offline for maintenance (excluded from search)
UPDATE storage_location SET current_status = 'MAINTENANCE' WHERE location_code = 'PNQ-SH-LN2-01';
UPDATE hospital SET status = 'SUSPENDED' WHERE hospital_id = 13;
UPDATE patient SET status = 'INACTIVE' WHERE diagnosis = 'Aplastic Anemia (in remission)';
UPDATE donor SET status = 'DEFERRED' WHERE donor_id = 41;
UPDATE donor SET status = 'WITHDRAWN' WHERE donor_id = 42;
SET @app_user_id = NULL;

-- ---------------------------------------------------------------------
-- Scenario map (request_id -> what it demonstrates)
--   request 1: SHORTLISTED Same-district match exists (Chennai), so state and national tiers are not used
--   request 2: SHORTLISTED Nothing in Madurai; falls back to Tamil Nadu even though Delhi has a 6/6
--   request 3: SHORTLISTED Nothing in Kerala; falls back to national search
--   request 4: APPROVED    No compatible unit anywhere in India
--   request 5: ALLOCATED   Allocated, transplant not yet scheduled
--   request 6: SCHEDULED   Transplant scheduled
--   request 7: COMPLETED   Completed, engrafted
--   request 8: COMPLETED   Completed with complications, national match
--   request 9: PENDING     background request
--   request 10: PENDING     background request
--   request 11: PENDING     background request
--   request 12: REJECTED    background request
--   request 13: CANCELLED   background request
-- ---------------------------------------------------------------------
